### TRACK READ ###
POST http://localhost:3000/newsletter-read/track?email=marie@gmail.com&id=1
Accept: application/json
Content-Type: application/json

### GET TOP NEWSLETTERS ###
GET http://localhost:3000/newsletter-read/top-newsletters
Accept: application/json

### GET TOP READERS ###
GET http://localhost:3000/newsletter-read/top-readers
Accept: application/json

### GET READ HISTORY BY USER ###
GET http://localhost:3000/newsletter-read/user-history?email=andressa@gmail.com
Accept: application/json